# Generated by Django 4.1.13 on 2025-04-24 20:37

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('ubicacion', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('minimo', models.IntegerField(default=0)),
                ('lotes', djongo.models.fields.JSONField()),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.farmacia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.producto')),
            ],
        ),
    ]
